### PR TITLE
Swap out broccoli-writer for broccoli-caching-writer

### LINKED ISSUE #11: Use of this module (via ember-cli-svgstore) breaks ember-cli hot css reloads
According to this issue: https://github.com/salsify/ember-cli-svgstore/issues/4 (and this thread http://discuss.emberjs.com/t/hot-reloading-css-reloads-complete-page/10729/4), using ember-cli-svgstore breaks css hot reloading, and needs a fix in this repo to resolve.

The assumption the linked issue makes is that the broccoli cache is busted by this module, which makes intuitive sense. I'll try swapping in `broccoli-caching-writer` and report back here.

### PR DESCRIPTION
**Pull request by jesseditson**
- fixes livereload in consuming ember-cli addons
- also remove checked in npm-debug.log
- update to latest broccoli-plugin API

Fixes #11

### CODE REVIEW

**Comment by BrianSipple** [comment]
Hi @jesseditson,

Thanks for this!... but have you taken a look at #5 yet? It handles these issues and a few more. I apologize for not having tended to it sooner, as I was thinking it might need to wait on [using svgstore](https://github.com/svgstore/broccoli-svgstore/issues/10) for this project, but I think it's actually ready to go now.

**Comment by jesseditson** [comment]
Interesting! I didn't see that issue, it looks like it was closed without merging, so it won't show up in the GH UI by default (I generally assume closed issues to be resolved/wontfix, but realize that can be a faulty assumption).

It seems like there's some traction towards stabilization, but since I needed this functionality this afternoon, I figured I'd hack it on. No worries if this isn't the PR that does it, as long as one does (soon?).

Any idea on timeline for a major bump?

**Comment by BrianSipple** [comment]
@jesseditson Ugh... I used the wrong link. [This is the PR](https://github.com/svgstore/broccoli-svgstore/pull/8) I was referring to. 

I just merged it a few hours ago and released 0.2.0

**Comment by jesseditson** [comment]
Ahhh! Fantastic! I'll jump over to the ember addon and throw a PR up that updates this to 0.2.0!

**Pull request closed without merging**
