### PR TITLE
Adding an option to retain file paths for symbol ids

### PR DESCRIPTION
**Pull request by sglanzer-fire**
We're currently using this plugin to create icon packs pulled from various Ember addon projects.  However, for legacy support I need to allow sub-directories to be part of the symbol id (e.g. `app/logo`, `badges/total`)

This adds a `flatten` option that defaults to the current behavior (`logo`, `total`), but retains the sub-directory paths if set to false (`app/logo`, `badges/total`)

I'm not sure where the npm-debug.log came from...

### CODE REVIEW

**Comment by BrianSipple** [comment]
Hi Steven! 

Since this project has moved to getting its [svg-to-symbol conversion implementation from `svgstore`](https://github.com/svgstore/broccoli-svgstore/issues/10), we should focus on trying to implement this there. 

The only potential change I'm seeing is to make the id generation a bit more configurable; after a few [recent additions](https://github.com/svgstore/svgstore/pull/7), you should just be able to declare `preserveAspectRatio` directly as a custom attribute and have it JustWork™️

**Comment by BrianSipple** [comment]
@sglanzer I take that back a bit. `broccoli-svgstore` [passes an id into the `svgstore.add()` function](https://github.com/svgstore/broccoli-svgstore/blob/master/index.js#L74), so while we're good on attribute preservation, id's are still something we'd need to handle here.

**UPDATE**: I’ve just [PR’d a new feature](https://github.com/svgstore/broccoli-svgstore/pull/16) that would cover this. Please feel free to review it and test it out if you’d like.

**Comment by sglanzer-fire** [comment]
@BrianSipple awesome, I'll give that a shot over the next week - thanks for the update!

**Comment by sglanzer-fire** [comment]
Quite a bit longer than a week, but just wanted to let you know that we've pulled this into our core dependency tree and no longer use a fork of the project, thanks!

**Pull request closed without merging**
